#!/bin/bash

alias hdu='du -h . | grep "^[0-9\.]\+G"'

alias dir="ls -laGh"
alias tu='top -o cpu'       # cpu
alias tm='top -o vsize'     # Memory

alias ccache='dscacheutil -flushcache'

alias to.stc='cd ~/Workspace/ios/SpazSoft/StackCalc.Swift'
alias to.spzt='cd ~/Workspace/ios/SpazSoft/SPZTracker'
alias to.w='cd ~/Workspace'
alias to.rails='cd ~/Workspace/rails'
alias to.ruby='cd ~/Workspace/ruby'
alias to.ios='cd ~/Workspace/ios'
alias to.ios.spz='cd ~/Workspace/ios/Spazsoft'
alias to.dot='cd ~/.dotfiles'
alias to.rt='cd ~/Movies/Developer/RubyTapas'
alias to.python='cd ~/Workspace/python'
alias to.down='cd ~/Downloads'
alias to.doc='cd ~/Documents'
alias to.swift='cd ~/Workspace/swift'
alias to.web='cd ~/Workspace/web'
alias to.mac='cd ~/Workspace/mac'
alias to.android='cd ~/Workspace/android'
alias to.md='cd ~/Library/Mobile\ Documents'
alias to.play=" cd ~/Workspace/playgrounds"

alias ws.p='python -m SimpleHTTPServer'

alias isotime='ruby -r time -e "puts Time.now.utc.iso8601"'

alias opensim='cd `appcontainer`'
# alias python='python3'
# alias pip='pip3'

# Android
alias find.git='find . -name .git -type d -prune'

alias pd='sips -g pixelWidth -g pixelHeight'

function xc_clean {
  rm -rf ~/Library/Caches/com.apple.dt.Xcode/
  rm -rf ~/Library/Developer/Xcode/DerivedData/
}

function jc () {
  curl -s ${1} | json
}

function archive.rt {
  pushd ~/Movies/Developer/RubyTapas
  mv ~/Downloads/*.mp4 .
  ga .
  gc -m "Todays episode"
  gp
  popd
}

alias rgrd='vsplit_tab "bundle exec guard"'
alias rser='vsplit_tab rs'
alias rpry='pry -r ./config/environment -r rails/console/app -r rails/console/helpers'
alias roa='split_tab "bundle exec guard" && rser'
alias ora='chrome http://localhost:3000'

# Dump Developer Certificates
alias dump.ident='security find-identity -v -p codesigning'

# POW Aliases
alias pow.restart='touch ~/.pow/restart.txt'
alias pow.restart_app='touch tmp/restart.txt'
alias pow.cfg='curl -H "Host: pow" -s http://localhost/config.json | json'
alias pow.status='curl -H "Host: pow" -s http://localhost/status.json | json'
alias pow.env='curl -H "Host: pow" -s http://localhost/env.json | json'

alias ssh-cs='ssh-add ~/.ssh/codespace_ssh_key'
alias ssh-syn='ssh-add ~/.ssh/id_synology'

# Glyph
alias glyph='open ~/Workspace/html/glyphicons_pro/glyphicons/web/html_css/index.html'

# Quicklook
alias ql='qlmanage -p $@'

# Frequent Directories
alias ss='cd ~/Workspace/rails/spazsoft4'
alias flsc='rm -rf ~/tmp/*'

# Edit and reload shell configurations
alias reload='source ~/.zshrc'
alias edot='st ~/.dotfiles'

function popcommands {
  history |
    awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' |
    sort -rn |
    head
}

function new_rails {
  scrolls new ${1} -s rspec capybara guard
  cd ${1}
  rails g controller Welcome index
}

# Create a new rails application using the app_template
function nr {
  rails new ${1} --skip-test-unit -m ~/.dotfiles/rails/app_template.rb
}

# File & Directory finding aliases
alias ff='noglob find . -type f -name '
alias ff.h='noglob find ~ -type f -name '
alias fd='noglob find . -type d -name '
alias fd.h='noglob find ~ -type f -name '

# Command that makes a directory and optionally change into it
# once it has been created
function mdc {
  mkdir -p "$1" && cd "$1"
}

# Command that creates a file and launches the editor on it
function mf {
  touch $1
  edit $1
}

# Commands used to testing a rails application in production mode
function rails_production {
  # RAILS_ENV=production bundle exec rake db:migrate
  # RAILS_ENV=production bundle exec rake db:seed
  RAILS_ENV=production bundle exec rake assets:precompile
  RAILS_ENV=production bundle exec rails s
}
function rails_production_cleanup {
  rm -rf public/assets/*
}

# Command used to reset rails database
function rails_reset_db {
  rm db/development.sqlite3 db/test.sqlite3
  bundle exec rake db:setup
}

# Open a local file
function chrome {
  open $@ --args --allow-file-access-from-files
}
alias chrome.ss='chrome http://www.spazstik-software.com'
alias chrome.lss='chrome http://spazsoft.dev'


function nrs {
  pushd . > /dev/null
  cd ~/bin > /dev/null
  newrubyscript $1
  edit $1
  popd > /dev/null
}

function mountAndroid {
  hdiutil attach ~/Development/android-source/android.dmg.sparseimage -mountpoint /Volumes/android
}

function code () {
    if [[ $# = 0 ]]
    then
        open -a "Visual Studio Code"
    else
        [[ $1 = /* ]] && F="$1" || F="$PWD/${1#./}"
        open -a "Visual Studio Code" --args "$F"
    fi
}
